openapi: 3.0.0
info:
  title: Token API
  version: 1.0.0
  description: API per la gestione di token JWT, Macaroon e PASETO

paths:
  /jwt/create:
    post:
      summary: Crea un token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JwtCreateRequest'
      responses:
        '200':
          description: Token JWT creato con successo
        '400':
          description: Richiesta non valida

  /jwt/verify:
    get:
      summary: Verifica un token JWT
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
          description: Il token JWT da verificare
        - in: query
          name: subject
          required: true
          schema:
            type: string
          description: Il soggetto per cui verificare il token
      responses:
        '200':
          description: Token JWT verificato con successo
        '400':
          description: Richiesta non valida

  /macaroon/create:
    post:
      summary: Crea un Macaroon
      parameters:
        - in: query
          name: location
          required: true
          schema:
            type: string
          description: La posizione per il Macaroon
        - in: query
          name: identifier
          required: true
          schema:
            type: string
          description: L'identificatore per il Macaroon
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
              description: Lista di caveat per il Macaroon
      responses:
        '200':
          description: Macaroon creato con successo
        '400':
          description: Richiesta non valida

  /macaroon/verify:
    get:
      summary: Verifica un Macaroon
      parameters:
        - in: query
          name: macaroon
          required: true
          schema:
            type: string
          description: Il Macaroon da verificare
      responses:
        '200':
          description: Macaroon verificato con successo
        '400':
          description: Richiesta non valida

  /paseto/local/create:
    post:
      summary: Crea un token PASETO locale
      parameters:
        - in: query
          name: footer
          required: false
          schema:
            type: string
          description: Footer opzionale per il token PASETO
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: Dati da includere nel token PASETO
      responses:
        '200':
          description: Token PASETO creato con successo
        '400':
          description: Richiesta non valida

  /paseto/local/verify:
    get:
      summary: Verifica un token PASETO
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
          description: Il token PASETO da verificare
        - in: query
          name: subject
          required: true
          schema:
            type: string
          description: Il soggetto per cui verificare il token
      responses:
        '200':
          description: Token PASETO verificato con successo
        '400':
          description: Richiesta non valida

components:
  schemas:
    JwtCreateRequest:
      type: object
      properties:
        sub:
          type: string
          description: Il soggetto del token
        iss:
          type: string
          description: L'issuer del token
        aud:
          type: array
          items:
            type: string
          description: Gli audience del token
        exp:
          type: integer
          format: int64
          description: La data di scadenza del token (in epoch time)
        nbf:
          type: integer
          format: int64
          description: Non valido prima di questa data (in epoch time)
        iat:
          type: integer
          format: int64
          description: La data di emissione del token (in epoch time)
